server:
  port: 8501

spring:
  application:
    name: api-gateway-service

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8500/eureka}
  instance:
    preferIpAddress: true
