server:
  port: 8070

spring:
  application:
    name: api-gateway-service
  cloud:
    gateway:
      routes:
        - id: placesModule
          uri: lb://PLACES-SERVICE
          predicates:
            - Path=/api/places-service/**
          filters:
            - RewritePath=/api/places-service, /
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: "http://192.168.1.114:3000"
            allowedHeaders: "*"
            allowedMethods:
              - GET
              - POST
eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8500/eureka}
  instance:
    preferIpAddress: true
