server:
  port: 8502

spring:
  data:
    couchbase:
      bucketName: code-exist
      scopeName: proxi-explore
      placesCollectionName: places
      locationCollectionName: location
  application:
    name: places-service
  couchbase:
    env:
      timeouts:
        view: 15000
        query: 15000
    connection-string: couchbase://192.168.1.114
    username: Administrator
    password: Taha1919gokce!

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://192.168.1.114:8500/eureka}
  instance:
    preferIpAddress: true

integration:
  google:
    baseUrl: https://places.googleapis.com/v1
    key: YOUR_API_KEY
    api:
      places:
        path: /places
        searchNearbyPath: :searchNearby
        fieldMask: places.id,places.location,places.internationalPhoneNumber,places.formattedAddress,places.displayName,places.primaryTypeDisplayName
